### ISSUE TITLE
meer info button

### ISSUE THREAD

**Issue by KoopReynders** [Joycemulder/Frondend-for-Designers#3]
Je zegt

> de tekst van mijn button niet geswapt krijg van Meer info naar close. Maar de "pop-up" toggled wel.

Wat ik niet snap aan je code is dit stuk:

https://github.com/Joycemulder/Frondend-for-Designers/blob/9673e9686e6f24dce6916517b450dd6e1096108e/Opdracht%203/js/javascript.js#L71

Je schrijft daar dat de innerhtml moet veranderen. Maar wanneer wordt die code uitgevoerd?
De toggle voor de popup heb je aan een click-event gekoppeld. Dus als dat gebeurt, dan wordt die code uitgevoerd. Wanneer wordt de code van de innerthtml uitgevoerd?

**Comment by Joycemulder** [comment]
@KoopReynders Ik zie wel dat die innerhtml niet een toggle heeft op de click. Ik zie alleen niet hoe ik dat kan maken zodat dat wel gebeurd.

**Comment by KoopReynders** [comment]
Bij de click eventlistener doe je nu een classlist toggle voor de popup. 
Daar kun je dan ook de innerhtml van de betreffende button veranderen !

**Comment by Joycemulder** [comment]
@KoopReynders Ik heb van alles geprobeerd maar niks lukt. Ook gekeken naar een tweede ui event maar snap er helemaal niks van. Wordt er beetje moedeloos van want wil het gewoon af hebben en niet nog weken aan zitten. Alles wat ik op zoek ik kom er gewoon niet uit.

**Comment by KoopReynders** [comment]
Kun je je nieuwe code, waarin je dingen hebt uitgeprobeerd (liefst met wat comments in je javascript file) op Github zetten. Dan ga ik kijken of ik je kan helpen.

**Comment by Joycemulder** [comment]
Ik heb er 2 buttons van gemaakt dat werkt wel soort van alleen is het niet super mooie oplossing. @KoopReynders

**Comment by KoopReynders** [comment]
Aha. Ik zie het. 
Nou ja .. als het werkt dan werkt het. Right?

Maar dat kan wel wat netter inderdaad:

Ik heb ook even met je code gespeeld. Ik heb aan de addEventlistener functie toegevoegd dat de button de innerhtml moet veranderen als er op geklikt wordt. In je code stond een if/else, maar die werd maar 1 keer uitgevoerd, op het moment dat de button werd aangemaakt.
Dat is wat je wil: Als er op de button wordt geklikt, komt er een popup, en dan wil je ook dat de button tekst verandert. Dus als je dat aan de click eventlistener functie toevoegt, dan wordt die code uitgevoerd.

Hoe ziet dat er uit?
```
      infobutton.addEventListener("click", function () {
          console.log("click");
          this.info.classList.toggle('active');

          //wat is de tekst van de button als er wordt geklikt? even console loggen ... 
          //gebruik 'this' om te verwijzen naar het object zelf, dat is hier dus de één van de infobuttons
          console.log("wat is de button tekst nu?",this.innerHTML);

          //als de tekst 'meer info' is dan veranderen in 'close', en andersom ...
          //deze if/else had je eerst hierboven staan bij het aanmaken van de button.
          //nu wordt die iedere keer dat er wordt geklikt op een button weer uitgevoerd.
          if(this.innerHTML == "Meer info"){ 
              this.innerHTML = "Close";
          }else{
              this.innerHTML = "Meer info";
          }

      }); 
```

**Comment by KoopReynders** [comment]
Ik vind trouwens jouw dubbele button truuk ook goed bedacht.
Het toont wel aan dat je begrijpt wat je aan het doen bent, én kan maken wat je wil. 
Op deze manier kun je dus best 'even snel' een demo maken en testen. 

Niets mis met deze 'truuk' !

**Comment by Joycemulder** [comment]
@KoopReynders o god. Ik zag dat ergens voorbij komen dat this.innerhtml maar wist niet goed wat de this. in hield dus had dat niet geprobeerd. Hahah stom. Hmm maar even proberen nu snap ik het wel wat beter. 

Thanks voor the compliment ^^. Ik snap het ook ergens wel alleen zijn dingen die nieuw zijn altijd zo lastig maar goed vallen en opstaan dan kom je er wel.
