### ISSUE TITLE
Escape key event javascript

### ISSUE THREAD

**Issue by Joycemulder** [Joycemulder/Frondend-for-Designers#4]
I have trouble with the escape key event in javascript. Can anybody help me with that?

**Comment by Joycemulder** [comment]
https://github.com/Joycemulder/Frondend-for-Designers/tree/master/Opdracht%203

**Comment by shoutoutloud** [comment]
Hi. What is the issue?

**Comment by iamdaniel0802** [comment]
Hi. The button is not listening for keyup event, hence the issue.

More comments  in fork;
https://github.com/iamdaniel0802/Frondend-for-Designers/blob/master/Opdracht%203/js/javascripts.js#L118

**Comment by Joycemulder** [comment]
Thanks will check it out @iamdaniel0802 .
@shoutoutloud I just don't understand when i click on meer info and the pop-up is up. How i can close it with the esc key.
